name: Run node app and deploy static page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install ./api

      - name: Run node app
        run: node ./api/app.js

      - name: Deploy static page
        uses: actions/deploy-pages@v1
        with:
          source: public
